# Anchor.toml for the `sodap` Anchor/Rust workspace
# ================================================

[toolchain]
# Use Yarn and Anchor 0.31.1
package_manager = "yarn"
anchor_version   = "0.31.1"

[programs.localnet]
# This must match the `declare_id!()` in your lib.rs
sodap = "4eLJ3QGiNrPN6UUr2fNxq6tUZqFdBMVpXkL2MhsKNriv"

[provider]
# Where to deploy and which keypair to use
cluster    = "localnet"
wallet     = "~/.config/solana/id.json"
# (Optional) default commitment for RPC calls
commitment = "processed"

[registry]
# If you're using a custom Anchor registry
url = "https://api.apr.dev"

[features]
# Enable workspace resolution & skip linting
resolution = true
skip-lint  = true

[scripts]
# Build the BPF program
build     = "anchor build"
# Deploy to localnet
deploy    = "anchor deploy --provider.cluster localnet"
# Run your on-chain tests
test      = "anchor test"
# After building, copy the generated IDL & TypeScript into your frontend
postbuild = "cp target/idl/sodap.json ../sodap-front/src/idl/sodap.json && cp target/types/sodap.ts ../sodap-front/src/idl/sodap.ts"

[test.validator]
# Reset validator state before tests
reset = true
